######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 18 20:49:56 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
